require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
RSpec/FilePath:
  Enabled: false

Metrics/AbcSize:
  Max: 24

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 9

Rails/I18nLocaleTexts:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/RedundantConstantBase:
  Exclude:
    - 'config/environments/production.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 120
  Exclude:
    - 'bin/bundle'
